/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.android.quakereport;

import android.app.LoaderManager;
import android.content.AsyncTaskLoader;
import android.content.Context;
import android.content.Intent;
import android.content.Loader;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;

import java.util.ArrayList;
import java.util.List;

public class EarthquakeActivity extends AppCompatActivity implements LoaderManager.LoaderCallbacks<List<Earthquake>> {

    public static final String LOG_TAG = EarthquakeActivity.class.getName();
    /**
     * Default request for USGS, earthquakes around Kosovo.
     */
    private static final String DEFAULT_REQUEST = "http://earthquake.usgs.gov/fdsnws/event/1/" +
            " query?format=geojson&starttime=10160101&endtime=20170101&minmagnitude=5" +
            "&latitude=42.6629&longitude=21.1655" +
            "&maxradiuskm=100";
    private EarthquakeAdapter mAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.earthquake_activity);

        // Find a reference to the {@link ListView} in the layout
        ListView earthquakeListView = (ListView) findViewById(R.id.list);

        // Create a new {@link ArrayAdapter} of earthquakes
        mAdapter = new EarthquakeAdapter(this, new ArrayList<Earthquake>());


        // Set the adapter on the {@link ListView}
        // so the list can be populated in the user interface
        earthquakeListView.setAdapter(mAdapter);

        // Set the item click listener on the {@link ListView}
        // so that the listener can respond on item click events
        earthquakeListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long rowId) {

                // Clicked earthquake
                Earthquake clickedEarthquake = mAdapter.getItem(position);

                // Details url for the selected earthquake
                String detailsUrl = clickedEarthquake.getDetails();

                // Open details web-page for the clicked earthquake
                openWebPage(detailsUrl);
            }
        });

        // Kick-off loader to get Erthquakes from the internet
        getLoaderManager().initLoader(0, null, EarthquakeActivity.this);

    }

    /**
     * Helper method for starting a a web-browser,
     * to display  earthquake details.
     */
    public void openWebPage(String url) {
        Uri webpage = Uri.parse(url);
        Intent intent = new Intent(Intent.ACTION_VIEW, webpage);
        if (intent.resolveActivity(getPackageManager()) != null) {
            startActivity(intent);
        }
    }

    /**
     * Helper method for updating UI with the data from USGS web-site
     */
    private void updateUI(final List<Earthquake> earthquakes) {
        mAdapter.loadEarthquakeList(earthquakes);
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     * @param id   The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    @Override
    public Loader<List<Earthquake>> onCreateLoader(int id, Bundle args) {
        return new EarthquakeLoader(EarthquakeActivity.this, DEFAULT_REQUEST);
    }

    /**
     * Called when a previously created loader has finished its load
     *
     * @param loader      The Loader that has finished.
     * @param earthquakes The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader<List<Earthquake>> loader, List<Earthquake> earthquakes) {
        if (earthquakes == null) {
            return;
        }
        // Update user interface if there erthquakes from USGS web-site.
        updateUI(earthquakes);
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader<List<Earthquake>> loader) {

    }

    /**
     * Getting Earthquakes Task, consists of crating an URl, making a HTTP request
     * getting the response and using it to make a list of earthquakes
     * Task is done using Loader Framework
     */
    private static class EarthquakeLoader extends AsyncTaskLoader<List<Earthquake>> {

        private String mUrl;

        public EarthquakeLoader(Context context, String url) {
            super(context);

            mUrl = url;

        }

        @Override
        protected void onStartLoading() {
            forceLoad();
        }

        @Override
        public List<Earthquake> loadInBackground() {
            // List of earthquakes
            ArrayList<Earthquake> earthquakes;
            // Get earthquakes form USGS
            earthquakes = QueryUtils.getEarthquakes(mUrl);

            return earthquakes;
        }
    }
}
